{{ $root := $.Values }}

{{- range $namespace := $root.namespaces }}
  {{- range $secret := $root.secrets }}

---
apiVersion: v1
kind: Secret
type: {{ default "Opaque" $secret.type }}
metadata:
  name: {{ $secret.name }}
  namespace: {{ $namespace }}

data:
  {{- range $k, $v := $secret.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}

  {{- end }}
{{- end }}
